"""Housing definitions, purchases, and playable menu."""

from game.housing.service import (
    FACILITIES,
    RESIDENCES,
    RESIDENCES_BY_KEY,
    AlreadyLivingThereError,
    HousingError,
    InsufficientCashError,
    ResidenceDefinition,
    ResidencePurchaseResult,
    UnknownResidenceError,
    comfort_for,
    get_player_residence,
    get_residence,
    gym_gain_bonus,
    recovery_bonus,
    housing_menu,
    purchase_residence,
    facility_for,
)

__all__ = [
    "RESIDENCES",
    "FACILITIES",
    "RESIDENCES_BY_KEY",
    "AlreadyLivingThereError",
    "HousingError",
    "InsufficientCashError",
    "ResidenceDefinition",
    "ResidencePurchaseResult",
    "UnknownResidenceError",
    "comfort_for",
    "get_player_residence",
    "get_residence",
    "gym_gain_bonus",
    "recovery_bonus",
    "housing_menu",
    "purchase_residence",
    "facility_for",
]
