"""Legal careers, timed shifts, and promotions."""

from game.jobs.definitions import (
    CAREERS,
    CAREERS_BY_KEY,
    JOB_ROLES_BY_KEY,
    CareerDefinition,
    JobRoleDefinition,
    get_career,
    get_job_role,
)
from game.jobs.service import (
    SHIFT_SECONDS,
    AlreadyEmployedError,
    EmploymentResult,
    InsufficientEnergyError,
    JobError,
    JobRestrictedError,
    NoShiftError,
    NotEmployedError,
    ShiftAlreadyActiveError,
    ShiftCompletionResult,
    ShiftNotCompleteError,
    ShiftStartResult,
    ShiftState,
    UnknownCareerError,
    complete_shift,
    get_shift_state,
    jobs_menu,
    join_career,
    start_shift,
)

__all__ = [
    "CAREERS",
    "CAREERS_BY_KEY",
    "JOB_ROLES_BY_KEY",
    "SHIFT_SECONDS",
    "AlreadyEmployedError",
    "CareerDefinition",
    "EmploymentResult",
    "InsufficientEnergyError",
    "JobError",
    "JobRestrictedError",
    "JobRoleDefinition",
    "NoShiftError",
    "NotEmployedError",
    "ShiftAlreadyActiveError",
    "ShiftCompletionResult",
    "ShiftNotCompleteError",
    "ShiftStartResult",
    "ShiftState",
    "UnknownCareerError",
    "complete_shift",
    "get_career",
    "get_job_role",
    "get_shift_state",
    "jobs_menu",
    "join_career",
    "start_shift",
]
