"""Data-driven district gyms and training rules."""

from game.gym.formula import (
    HAPPINESS_PER_TRAIN,
    STANDARD_ENERGY_PER_TRAIN,
    STAT_GAIN_PER_STANDARD_TRAIN,
    WEIGHT_CLASS_ENERGY,
    TrainingOutcome,
    gain_per_train,
    trains_for,
    training_outcome,
    validate_training_energy,
)

from game.gym.definitions import (
    DEFAULT_GYM_KEY,
    GYMS,
    GYMS_BY_KEY,
    GymDefinition,
    get_district_gyms,
    get_gym,
)
from game.gym.service import (
    TRAINING_ENERGY_COST,
    TRAINING_STAT_GAIN,
    VALID_BATTLE_STATS,
    GymAlreadyUnlockedError,
    GymError,
    GymLevelError,
    GymLocationError,
    GymLockedError,
    GymMembershipFundsError,
    GymSelectionResult,
    GymStatUnavailableError,
    GymUnlockResult,
    UnknownGymError,
    calculate_training_gain,
    display_training_block,
    get_training_block,
    get_unlocked_gyms,
    gym_menu,
    select_gym,
    train,
    unlock_gym,
)

__all__ = [
    "HAPPINESS_PER_TRAIN",
    "STANDARD_ENERGY_PER_TRAIN",
    "STAT_GAIN_PER_STANDARD_TRAIN",
    "WEIGHT_CLASS_ENERGY",
    "TrainingOutcome",
    "gain_per_train",
    "trains_for",
    "training_outcome",
    "validate_training_energy",
    "DEFAULT_GYM_KEY",
    "GYMS",
    "GYMS_BY_KEY",
    "TRAINING_ENERGY_COST",
    "TRAINING_STAT_GAIN",
    "VALID_BATTLE_STATS",
    "GymAlreadyUnlockedError",
    "GymDefinition",
    "GymError",
    "GymLevelError",
    "GymLocationError",
    "GymLockedError",
    "GymMembershipFundsError",
    "GymSelectionResult",
    "GymStatUnavailableError",
    "GymUnlockResult",
    "UnknownGymError",
    "calculate_training_gain",
    "display_training_block",
    "get_district_gyms",
    "get_gym",
    "get_training_block",
    "get_unlocked_gyms",
    "gym_menu",
    "select_gym",
    "train",
    "unlock_gym",
]
