"""Data-driven district gyms and training rules."""

from game.gym.definitions import (
    DEFAULT_GYM_KEY,
    GYMS,
    GYMS_BY_KEY,
    GymDefinition,
    get_district_gyms,
    get_gym,
)
from game.gym.service import (
    TRAINING_ENERGY_COST,
    TRAINING_STAT_GAIN,
    VALID_BATTLE_STATS,
    GymAlreadyUnlockedError,
    GymError,
    GymLevelError,
    GymLocationError,
    GymLockedError,
    GymMembershipFundsError,
    GymSelectionResult,
    GymStatUnavailableError,
    GymUnlockResult,
    TrainingResult,
    TrainingRestrictedError,
    UnknownGymError,
    calculate_training_gain,
    display_training_block,
    get_training_block,
    get_unlocked_gyms,
    gym_menu,
    select_gym,
    train,
    unlock_gym,
)

__all__ = [
    "DEFAULT_GYM_KEY",
    "GYMS",
    "GYMS_BY_KEY",
    "TRAINING_ENERGY_COST",
    "TRAINING_STAT_GAIN",
    "VALID_BATTLE_STATS",
    "GymAlreadyUnlockedError",
    "GymDefinition",
    "GymError",
    "GymLevelError",
    "GymLocationError",
    "GymLockedError",
    "GymMembershipFundsError",
    "GymSelectionResult",
    "GymStatUnavailableError",
    "GymUnlockResult",
    "TrainingResult",
    "TrainingRestrictedError",
    "UnknownGymError",
    "calculate_training_gain",
    "display_training_block",
    "get_district_gyms",
    "get_gym",
    "get_training_block",
    "get_unlocked_gyms",
    "gym_menu",
    "select_gym",
    "train",
    "unlock_gym",
]
